version: '3.7'

services:
  database:
    image: postgres
    ports:
      - ${DB_PORT}:5432
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  api:
    build: .
    restart: always
    depends_on:
      - database
    ports:
      - ${FLASK_PORT}:5000
    container_name: flask-api
    volumes:
      - .:/app

volumes:
  pgdata: