version: '3.7'

services:
  # Database service
  database:
    # Image to be built
    image: postgres
    ports:
      - ${DB_PORT}:5432
    restart: always
    # Enviroment variables
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  api:
    # Build using the Dockerfile
    build: .
    restart: always
    # Waits for the database image to be built before starts to build
    depends_on:
      - database
    ports:
      - ${FLASK_PORT}:5000
    container_name: flask-api
    volumes:
      - .:/app
# Creates (if no exists) the local volume to persist the data
volumes:
  pgdata: